### PR TITLE
Update Makefile for CI and remove PR check script

### PR DESCRIPTION
**Pull request by jharrington22**
Updated to the `Makefile` to work with Origin CI and removed PR check script as we're running the two make targets in prow in parallel.

### CODE REVIEW

**Comment by vkareh** [comment]
Running `make` now changes the contents of `assets/bindata.go` - any chance we can commit the new version, or lock in to a specific version `go-bindata` so that it doesn't stage changes to assets on every go-bindata release?

**Comment by jharrington22** [comment]
@vkareh I was looking at locking the version of `go-bindata` specifying `@3.1.3` didn't seem to work. Let me look at it you are right its changing (had to remove my older version)

**Comment by vkareh** [comment]
@jharrington22 - what's the status of this? Can we merge as-is or does it need more work?

**Comment by jharrington22** [comment]
@vkareh I need to check the PR for openshift/release then we can merge this.

**Comment by vkareh** [comment]
This one: https://github.com/openshift/release/pull/9633 ?

**Comment by jharrington22** [comment]
@vkareh this is updated, once merged I'll remove the hold on openshift/release#9633

**Comment by vkareh** [comment]
@jharrington22 - can we merge this now or are we still waiting for more CI work?

**Comment by jharrington22** [comment]
@vkareh this is good to go.

**Pull request merged**
